### PR TITLE
Update to 2.1.1 Mender release components

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf I will need to merge this one, and then launch a similar PR for 2.2.1, so that the Artifact gets uploaded in both places

**Comment by lluiscampos** [comment]
Blocked by the final release build/publish. I'll retry the Pipeline later.

**Comment by lluiscampos** [comment]
> > I will need to merge this one, and then launch a similar PR for 2.2.1, so that the Artifact gets uploaded in both places
> 
> I don't think you need to do that actually. The GUI only uses the version-less link, so both versions will get the latest artifact. Which shouldn't be a problem, it should work on both.

So why are we keeping the versioned one? Can we remove it from the CI, then?

**Comment by kacf** [comment]
> So why are we keeping the versioned one? Can we remove it from the CI, then?

I think it's mostly for historical purposes. We can manually roll back to an earlier one if we break something for example. It's probably not super important to keep, but doesn't hurt either.

**Pull request merged**
