### PR TITLE
Update download links for 2.1.0 and beyond.

### PR DESCRIPTION
**Pull request by kacf**
For this we need to also update to a temporary build tag, but we will
switch to the real one shortly.

Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
The tests here are failing because we haven't generated the deb package for the 2.1.0b1-build3 tag.

**Comment by lluiscampos** [comment]
For just passing this PR, you can just set MENDER_VERSION to 2.0.0, leaving INTEGRATION and ARTIFACT to 2.1.0b1-build3.

The package is only used for testing so this suggested change should be fine IMO

**Comment by kacf** [comment]
It's also used for the artifact generator, which is in fact broken in 2.0.0 (there is a workaround in the Dockerfile). I think instead I will split it into `MENDER_VERSION` and `MENDER_DEB_VERSION` because I think we will hit this problem again and again, and the deb will always be uploaded later than the source tag.

**Comment by lluiscampos** [comment]
> I think instead I will split it into `MENDER_VERSION` and `MENDER_DEB_VERSION` because I think we will hit this problem again and again, and the deb will always be uploaded later than the source tag.

Good idea

**Comment by kacf** [comment]
I updated it in case you want to have a second look. Internally both are tested now, 2.1.0b1-build3 by qemu, and 2.0.0 by Raspbian.

**Comment by lluiscampos** [comment]
Looks good!

Nice commit message also

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
