### PR TITLE
Deploy on branch master

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Title

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
Is this what you had in mind?

**Comment by oleorhagen** [comment]
@kacf I have not handled the tags, should I remove both of them? or just the `latest` one we made?

**Comment by kacf** [comment]
Just remove both. They won't be useful anymore after this.

**Comment by oleorhagen** [comment]
Done! Merging now

**Pull request merged**
