### PR TITLE
QA-81: GitLab Pipeline completition

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf @mzedel This one will affect the upcoming release (this repo is deployed directly from master). Could one of you double check it?

**Comment by kacf** [comment]
It has to be merged first to be tested though. Or?

**Comment by lluiscampos** [comment]
> It has to be merged first to be tested though. Or?

I thought it was not necessary to test if you guys trusted the change.

But yes, I can test it the same way as I did in the first repos I was working with: make a tmp commit to publish in a different path, and then remove commit and clean-up S3. I'll do this now.

**Comment by lluiscampos** [comment]
It works :)

**Comment by lluiscampos** [comment]
There is one detail, though: the logic will always override the artifact in integration folder for every merge to master! This was already the situation in Travis, I just wanted to make you aware.

I have some creative ideas to avoid this. But they need discussion and I am unsure about the value.

**Pull request merged**
