### PR TITLE
MEN-3363 adjusted layout & for onboarding artifact demo site

### PR DESCRIPTION
**Pull request by mzedel**
this should support resolutions from small phone to 4k screens

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
Hmm, demo artifact doesn't work on the QEMU instance anymore? That's a bit discomforting. Probably not related to your change, but we should look into this. I could take a look at it tomorrow if you don't want to dig into the image testing yourself.

**Comment by lluiscampos** [comment]
> Hmm, demo artifact doesn't work on the QEMU instance anymore? That's a bit discomforting. Probably not related to your change, but we should look into this. I could take a look at it tomorrow if you don't want to dig into the image testing yourself.

@kacf The errors look worrying, indeed. You can leave it to me. I don't have time today, unfortunately, but I am going to look at this rather soon as it will be a blocker for the upcoming release.

**Comment by kacf** [comment]
Thanks!

**Comment by lluiscampos** [comment]
> Thanks!

@kacf After some local debugging I couldn't find anything wrong... I just restarted the job in CI and passed.

**Review by michaelatmender — APPROVED** [review]

**Pull request merged**
