### PR TITLE
Release 3.2 leftovers

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Went for the `mender-version` option :)

**Comment by lluiscampos** [comment]
By looking at the CI failure, it seems like we use the same variable for both the Docker image and the Git version.

**Comment by oleorhagen** [comment]
@lluiscampos see if this is sensible to you?

Just using `mender-3.2.1` causes a fair amount of issues, like downloading the source archive, due to it not being the tag name exact.

**Review by lluiscampos — APPROVED** [review]
I agree, this is an acceptable solution. Both strings are next to each other, very difficult to miss on releases...

Please tidy up a bit your commit history :pray:

**Pull request merged**
